#server相关配置
server:
  port: 8889
# ssf 相关配置
#datasource:
#  master:
#    url: jdbc:mysql://55f249971d6c1.gz.cdb.myqcloud.com:6900/bac?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
#    username: lcy
#    password: lcy123
#  include-stacktrace: always

jwt:
  signature: 7kFsxas4WG6aLLH5owLvevE8dIK32FfNDEV
  iss_str: yqwl
  #单位 天
  token_time_web: 1

swagger:
  enable: true
wxcp:
  pur:
    appid: wx897f40be2f4f09d4
    corpSecret: PxbGObg0rZ051X97NUtB6q-up2AOke8X9VjodEbV7cQ
    agentId: 1000002
    token: JQKPQ83qYQ34
    encodingAESKey: KxcVXPa3HvzA1JbrWvLINC3vkAwqSEmH1PedHrCchty


