#日志输出目录
logging:
  path: /tmp

#server相关配置
server:
  context-path: /vw

wxSmall:
    appid: wx435e85b65055ca74
    secret: 7eafa6d6c70e4ccac20953b1e281a063
#spring配置
spring:
  application:
    name: yqwl-base #应用名
  profiles:
    active: dev
  http:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  datasource:
  #外网数据库地址
    url: jdbc:mysql://rm-2ze64zm5i63d7geglmo.mysql.rds.aliyuncs.com:3306/changetable?useUnicode=true&&useSSL=false
  #内网数据库地址
   # url: jdbc:mysql://55f249971d6c1.gz.cdb.myqcloud.com:6900/fawdriver?useUnicode=true&&useSSL=false

    username: acy
    password: Picture123
    driver-class-name: com.mysql.jdbc.Driver
  cache:
    ehcache:
      config: classpath:/ehcache.xml
# 更多数据源
#custom:
#  datasource:
#    names: klySqlserver1
#    klySqlserver:
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      url: jdbc:sqlserver://10.24.142.220:1433;databaseName=faw-logi
#      username: mif
#      password: MESSAGE7088
# ssf 相关配置
#ssf:
#  swagger:
#    basePackage: com.qm.volkswagenChina
#  datasource:
#    master:
#      maxActive: 50
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

management:
  security:
    enabled: false


jwt:
  signature: 7kFsxas4WG6aLLH5owLvevE8dIK32FfNDEV
  iss_str: apollo
  #单位 天
  token_time_web: 1