#server相关配置
server:
  port: 8880
# ssf 相关配置
#datasource:
#  master:
#    url:
#    username:
#    password:
#  include-stacktrace: always

jwt:
  signature: 7kFsxas4WG6aLLH5owLvevE8dIK32FfNDEV
  iss_str: yqwl
  #单位 天
  token_time_web: 1

swagger:
  enable: true
wxcp:
  pur:
    appid: wx9a4a3e756d33a264
    corpSecret: PxbGObg0rZ051X97NUtB6q-up2AOke8X9VjodEbV7cQ
    agentId: 1000002
    token: JQKPQ83qYQ34
    encodingAESKey: KxcVXPa3HvzA1JbrWvLINC3vkAwqSEmH1PedHrCchty


